### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by ZiggsFizz** [zhenglab/spiralnet#2]
Thanks for your efforts.
The configuration file requires a 'fist' format for the dataset, how can I train the network using my dataset with 'jpg' format?

**Comment by Liuhongzhi2018** [comment]
We save the absolute path of images into flist files, which are stored on the server. And you could also modify the dataloader code according to the way you need.
https://github.com/zhenglab/spiralnet/blob/64503fb8936d3d3da2d1aabad68681c86cd8764a/src/dataset.py#L62
